### PR TITLE
null safety

### PR DESCRIPTION
**Pull request by Cat-sushi**
migration to null safety

### CODE REVIEW

**Comment by Outpox** [comment]
Hey, thanks for the PR. Could you elaborate/explains your changes please?  
I haven't used Dart in a while and I would like to understand the difference before I merge.

**Comment by Cat-sushi** [comment]
I'm afraid I'm not good at explaining.
I recommend you to read [Sound null safety | Dart](https://dart.dev/null-safety "Sound null safety"), instead.

In addition to above, I additionally passed  optional arguments `growable: false` to named `List` constructors `List.generate()` and `List.filled()` replacing the unnamed constructor `List(size)`, because the unnamed constructor generates fixed length lists, while named constructors generate growable lists by default which are very slow with subscripting.

**Review by Outpox — APPROVED** [review]

**Comment by Outpox** [comment]
I'm okay merging this, this will be released as a pre-release and breaking change as specified in the documentation.  
I will also fix the linting issues and then publish a new version.

Thanks again for the pull request 👍

**Comment by Outpox** [comment]
https://pub.dev/packages/edit_distance/versions/0.5.0-nullsafety.0

**Pull request merged**
