### PR TITLE
Feature/dart2.0.0 update

### PR DESCRIPTION
**Pull request by Outpox**
Hey there, I've updated the lib to be compatible with Dart 2.0.0  
I've also removed the quiver_iterable dependency as it was only required to get the min value of an array. I replaced it with `reduce` and `min` from the built-in math library.  
The tests runs fine.

### CODE REVIEW

**Comment by Outpox** [comment]
Hello @kseo 
Any update on this PR? :D

**Comment by kseo** [comment]
@Outpox Sorry for being late to respond. I no longer maintain the package. I will give you the admin permission if you want to take over the package.

**Comment by Outpox** [comment]
Hey @kseo !
No problem, I'm willing to over the package :-)

**Comment by kseo** [comment]
@Outpox Okay. What's your email address? I will add you to the list of uploaders.

**Comment by Outpox** [comment]
Great, thanks!
I sent you a mail to the address you used on https://pub.dev/packages/edit_distance

**Comment by kseo** [comment]
@Outpox I've sent an invitation to you. You will be added as uploader after you confirm it. Thanks!

**Comment by Outpox** [comment]
Invitation received and accepted! Thanks to you too :-)

**Pull request merged**
